#!/bin/bash

if [ $(id -u 2>/dev/null) -ne 0 ]; then
	echo "Please running as root ...!!!"
	exit 127
fi
packages=(
  firmware-brcm80211
  wireless-regdb
  wpasupplicant
)
apt-get update 2>&1 >/dev/null || exit $?
apt-get install --no-install-recommends --no-install-suggests ${packages[@]} || exit $?
modprobe -v brcmsmac || exit $?
